module.exports = {
    MTC_LIST: `button[name="MTC List"]`,
    COL_VEN_MTC: `a[name="Colombia Missionary Training Center- Venezuela Satellite"]`,
    BRAZIL_MTC: `a[name="Brazil Missionary Training Center"]`,
    COLOMBIA_MTC: `a[name="Colombia Missionary Training Center"]`, 
    ENGLAND_MTC: `a[name="England Missionary Training Center"]`,
    GHANA_MTC: `a[name="Ghana Missionary Training Center"]`,
    GUATEMALA_MTC: `a[name="Guatemala Missionary Training Center"]`,
    MEXICO_MTC: `a[name="México Missionary Training Center"]`,
    NZ_MTC: `a[name="New Zealand Missionary Training Center"]`,
    PERU_MTC: `a[name="Perú Missionary Training Center"]`,
    PHIL_MTC: `a[name="Philippines Missionary Training Center"]`,
    PROVO_MTC: `a[name="Provo Missionary Training Center"]`,
    S_AFRICA_MTC: `a[name="South Africa Missionary Training Center"]`,
    VACC_RULES: `a[name="Vaccination Rules"]`,
    IMZT_REQ: `a[name="Immunization Requirements"]`,
    LOC_REQ: `a[name="Location Requirements"]`,
    IMZT_EMAIL: `a[name="Immunization Reminder Emails"]`
}